Added a script for switching zellij sessions for git worktrees
Broke common project and picking logic out into separate scripts that
can be called from the session and the worktree scripts. Changed the
structure of the scripts directory to declutter.

diff --git a/scripts/zellij/create b/scripts/zellij/create
--- a/scripts/zellij/create
+++ b/scripts/zellij/create
@@ -1,17 +1,17 @@
 #!/bin/sh
 
+name=$1
+path=$2
+layout=$3
+
+if [ -z "$name" ]; then
+    echo "Session name required!" 2>&1
+    exit 1
+fi
+
 if [ "$ZELLIJ" = "0" ]; then
-    $DEV_SCRIPTS_DIR/zellij_switch_session $@
+    $DEV_SCRIPTS_DIR/zellij/switch "$name" "$path" "$layout"
 else
-    name=$1
-    path=$2
-    layout=$3
-
-    if [ -z "$name" ]; then
-        echo "Session name required!" 2>&1
-        exit 1
-    fi
-
     # enter directory if provided and it exists
     if [ -n "$path" ] && [ -d "$path" ]; then
         cwd=$(pwd)
